apiVersion: v1
kind: Service
metadata:
  labels:
    name: employee-microservice
    visualize: "true"
  name: employee-microservice
spec:
  ports:
    - port: 8001
      targetPort: 8001
  selector:
    name: employee-microservice
  sessionAffinity: None
  type: NodePort
  # type: LoadBalancer
